require 'rake/testtask'

Rake::TestTask.new do |task|
  task.libs << 'test' # adds the tests directory to the lists of directories in the #$LOADPATH
  task.test_files = FileList['test/*test*.rb']
  # creates a list of files that match "tests/test*.rb"
  task.verbose = true
  # if you want your tests to output what they should do, then set this to true.
end

task 'default' => 'test'

task 'hello' do
  p 'hello world!'
end


task 'gem' do
  sh 'gem build words1.gemspec'
  sh 'gem build words2.gemspec'
  sh 'gem build frequencies1.gemspec'
  sh 'gem build frequencies2.gemspec'
  sh 'gem install *.gem  --user-install'
  sh 'gem list -r words --local'
  sh 'gem list -r frequencies --local'
end

task 'gem-clean' do
  sh 'rm *.gem'
end

task 'ch20' do
  sh 'bundle install --local --quiet'
  sh 'bundle exec ruby ch_20-plugins.rb ../test/pride-and-prejudice-input.txt --quiet'
end